agent: DQN
device: cuda
experiment_name: DQN_Decay_10x10
hyperparameters:
  batch_size: 128
  epsilon: 1.0
  epsilon_decay: 0.99
  epsilon_min: 0.1
  epsilon_policy: decay
  gamma: 0.99
  hidden_size: 256
  num_layers: 4
  target_update: 5
maze_file: mazes/10x10.txt
save_dir: results/dqn/decay/
training:
  episodes: 500
  max_steps: 200
  render: true
viz:
  num_plots: 4
  window_size: null
