agent: Q-learning
experiment_name: Q_Learning_Maze_10x10_Performance
hyperparameters:
  alpha: 0.1
  epsilon: 1.0
  epsilon_decay: 0.99
  epsilon_min: 0.01
  epsilon_policy: performance_based
  gamma: 0.5
maze_file: mazes/10x10.txt
save_dir: results/q_learning/performance/
training:
  episodes: 500
  max_steps: 200
  render: true
viz:
  num_plots: 4
  window_size: null
