agent: Q-learning
experiment_name: Q_Learning_Maze_10x10_Decay
hyperparameters:
  alpha: 0.05
  epsilon: 1.0
  epsilon_decay: 0.99
  epsilon_min: 0.01
  epsilon_policy: decay
  gamma: 0.99
maze_file: mazes/20x20.txt
save_dir: results/q_learning/decay/
training:
  episodes: 500
  max_steps: 200
  render: true
viz:
  num_plots: 4
  window_size: null
