agent: DQN
device: cuda
experiment_name: DQN_Boltzmann_10x10
hyperparameters:
  batch_size: 128
  epsilon_policy: boltzmann
  gamma: 0.5
  hidden_size: 64
  num_layers: 2
  target_update: 5
  temperature: 1.0
  temperature_decay: 0.5
  temperature_min: 0.01
maze_file: mazes/10x10.txt
save_dir: results/dqn/boltzmann/
training:
  episodes: 500
  max_steps: 200
  render: true
viz:
  num_plots: 4
  window_size: null
