experiment_name: "DQN_Decay_20x20"
device: cuda  # 'cuda' for GPU acceleration or 'cpu'
agent: "DQN"
maze_file: "mazes/20x20.txt"

hyperparameters:
  hidden_size: 2048  # Increased hidden layer size for better feature extraction
  num_layers: 6
  gamma: 0.8  # Slightly higher discount factor to emphasize future rewards
  epsilon_policy: "decay"  # Exploration strategy
  epsilon: 1.0  # Initial epsilon
  epsilon_min: 0.05  # Lower minimum epsilon to allow more exploitation
  epsilon_decay: 0.85  # Slower decay for more initial exploration
  batch_size: 256  # Training batch size
  target_update: 10  # Target network update frequency

training:
  episodes: 1000  # Increased episodes for better learning in a larger maze
  max_steps: 400  # More steps per episode to account for the larger state space
  render: True

viz:
  num_plots: 4
  window_size: null

save_dir: "results/dqn/decay/"
