experiment_name: "Q_Learning_Maze_10x10_Boltzmann"
agent: "Q-learning"
maze_file: "mazes/15x15.txt"

hyperparameters:
  alpha: 0.075
  gamma: 0.75
  epsilon_policy: "boltzmann"  # Use Boltzmann exploration strategy
  temperature: 1.0  # Initial temperature
  temperature_min: 0.1  # Minimum temperature value
  temperature_decay: 0.75  # Temperature decay rate

training:
  episodes: 500
  max_steps: 200
  render: True

viz:
  num_plots: 4
  window_size: null

save_dir: "results/q_learning/boltzmann/"
