# Q-Learning with Epsilon Decay
experiment_name: "Q_Learning_Maze_10x10_Decay"
agent: "Q-learning"
maze_file: "mazes/15x15.txt"

hyperparameters:
  alpha: 0.05  # Learning rate for Q-learning updates
  gamma: 0.75  # Discount factor for future rewards
  epsilon_policy: "decay"  # Exploration strategy
  epsilon: 1.0  # Initial epsilon value
  epsilon_min: 0.01  # Minimum epsilon value
  epsilon_decay: 0.99  # Decay rate for epsilon

training:
  episodes: 500  # Number of episodes to train for
  max_steps: 200  # Maximum steps per episode
  render: True  # Enable visualization during training

viz:
  num_plots: 4  # Number of episodes for trajectory visualization
  window_size: null  # Auto-adjust moving average window size

save_dir: "results/q_learning/decay/"  # Output directory